version: 2
project_name: volume-mover

before:
  hooks:
    - npm --prefix webapp ci
    - npm --prefix webapp run build
    - go mod tidy
    - go test ./...

builds:
  - id: volume-mover
    main: ./cmd/volume-mover
    binary: volume-mover
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: david-loe
    name: volume-mover
